config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :authors
  resources :comments
  get '/' => 'authors#index'
  get '/introspect' => 'authors#introspect'
  get '/products' => 'authors#product'
  get '/career' => 'authors#career'
  get '/training' => 'authors#training'
  get '/contact' => 'comments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :email)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:name, :title, :description)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:firstName, :lastName, :phone, :email, :department, :job_title, :address, :race, :sex, :credit_card, :height, :marital_status, :startDate, :license, :lunchSpot, :employeeBenft, :vehicle, :vyear, :vmake, :vmodel, :vcarDescr, :vPlate, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/career.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" href="">
    </head>
    <body style="font-family:courier new;border:solid lightblue;border-width:.3px;background-color:black;height:700vh;">
<div class="navContainer">
  <a href="/"><img class="logo"src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/163148802_4423789508906_1467717329119223013_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=730e14&_nc_ohc=gL1IpFFdX_IAX-yc6EF&_nc_ht=scontent-dfw5-2.xx&oh=4d1d20289371456e6ae3fdf8b921896f&oe=607A2C90"></a>
      <a style="text-decoration:none;" href="/training"><div class="elNav">Training</div></a>
   <a style="text-decoration:none;" href="/introspect"> <div class="elNav">n2rOspeX</div></a>
    <a style="text-decoration:none;" href="/contact"><div class="elNav">e-Chat Room</div></a>
</div>


<img style="width:100%;" src="https://images.unsplash.com/photo-1508666709797-f0bb3d96324d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NDl8fHRlY2hub2xvZ3klMjBwcm9kdWN0c3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=60">

<h1 style="border:solid lightblue; color:white;text-align:center;">  Careers </h1>







          <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>  
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script >
    
        </script>
    </body>
</html>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/introspect.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" href="">
    </head>
    <body style="font-family:courier new;border:solid lightblue;border-width:.3px;background-color:black;height:700vh;">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<div class="navContainer">
  <a href="/"><img class="logo"src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/163148802_4423789508906_1467717329119223013_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=730e14&_nc_ohc=gL1IpFFdX_IAX-yc6EF&_nc_ht=scontent-dfw5-2.xx&oh=4d1d20289371456e6ae3fdf8b921896f&oe=607A2C90"></a>
      <a style="text-decoration:none;" href="/products"><div class="elNav">Products</div></a>
   <a style="text-decoration:none;" href="/introspect"> <div class="elNav">n2rOspeX</div></a>
    <a style="text-decoration:none;" href="/career"><div class="elNav">Careers</div></a>
</div>


<img style="width:100%;" src="https://images.unsplash.com/photo-1523908511403-7fc7b25592f4?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80">

<h1 style="color:lemonchiffon; text-align:center;margin-top:22px;" >Join The Team</h1>
<img style="height:auto;padding:1em;width:100%;"src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/163148802_4423789508906_1467717329119223013_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=730e14&_nc_ohc=gL1IpFFdX_IAX-yc6EF&_nc_ht=scontent-dfw5-2.xx&oh=4d1d20289371456e6ae3fdf8b921896f&oe=607A2C90">
<div class="empCard">
    <% Employee.all.each do |e| %>

    <h4 style="border:solid lightblue;text-align:center;background-color:lightblue;color: black;border-width:.3px;">  <%= e.firstName%>   <%= e.lastName%></h4>
    <div style="border:solid grey;border-width:.3px;height:200px;width:100%;"></div>
<br>
   Role:    CGBS <%= e.job_title%> <br>
    Dept: <%= e.department%>
    <h4 style="color:lightblue;text-align:right;"><%= e.phone%></h4>
    <hr>
    <%end%>        
</div>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>  
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script >
        
        
        
        </script>
    </body>
</html>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link rel="stylesheet" href="">
    </head>
    <body style="font-family:courier new;;border:solid lightblue;border-width:.3px;background-color:black;;height:700vh;">
    
        <div class="navContainer">
            <a href="/"> <img class="logo"src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/163148802_4423789508906_1467717329119223013_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=730e14&_nc_ohc=gL1IpFFdX_IAX-yc6EF&_nc_ht=scontent-dfw5-2.xx&oh=4d1d20289371456e6ae3fdf8b921896f&oe=607A2C90"></a>
            <a style="text-decoration:none;" href="/training"><div class="elNav">Products</div></a>
            <a style="text-decoration:none;" href="/introspect"> <div class="elNav">n2rOspeX</div></a>
            <a style="text-decoration:none;" href="/contact"><div class="elNav"> e-Chat Room</div></a>
        </div>


        <img style="width:100%;margin-bottom:45px;"src="https://images.unsplash.com/photo-1573497620053-ea5300f94f21?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80">


        <h1 class="cboard"><img class="logo"src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/163148802_4423789508906_1467717329119223013_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=730e14&_nc_ohc=gL1IpFFdX_IAX-yc6EF&_nc_ht=scontent-dfw5-2.xx&oh=4d1d20289371456e6ae3fdf8b921896f&oe=607A2C90">Virtual ChatRoom </h1>
        <div style="margin:1em;border-width:.3px;border-radius:22px;font-size:22px;text-align:center;color:white;text-decoration:none;"><%= link_to ' (+) Add New Comment   ', new_comment_path %></div>
<div class="phantomDiv"><span style="font-size:30px;color:yellow;"> Resolved: </span> What Initiatives Should Be Taken By CGBS to help innovate the demand of Responsible Technology ? </div>


<% Comment.all.each do |c| %>
    <div class="comContainer">

    <div class="com_screen">
        <%= c.title%><hr><br>
        <%= c.description%>
    </div>

    <div style="height:6vh;"></div>
        <div class="com_controller">
            <%= c.name%><br>
            <img class="logo" style="height:50px;" src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/163148802_4423789508906_1467717329119223013_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=730e14&_nc_ohc=gL1IpFFdX_IAX-yc6EF&_nc_ht=scontent-dfw5-2.xx&oh=4d1d20289371456e6ae3fdf8b921896f&oe=607A2C90">
        </div>
    </div>

<% end %>







        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>  
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script >
        
            // console.log($);
 const generateNewMessages = () =>{
        setInterval(function(){
                 $('.phantomDiv').prepend("  <%= Comment.create(
                    name:  Faker::TvShows::Community.characters  ,
                    title: Faker::Company.profession , 
                    description: Faker::Company.bs )%>");                 
                 
                }, 
                9999999999999);
 }
    
        </script>
    </body>
</html>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Department</th>
      <th>Job title</th>
      <th>Address</th>
      <th>Race</th>
      <th>Sex</th>
      <th>Credit card</th>
      <th>Height</th>
      <th>Marital status</th>
      <th>Startdate</th>
      <th>License</th>
      <th>Lunchspot</th>
      <th>Employeebenft</th>
      <th>Vehicle</th>
      <th>Vyear</th>
      <th>Vmake</th>
      <th>Vmodel</th>
      <th>Vcardescr</th>
      <th>Vplate</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstName %></td>
        <td><%= employee.lastName %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.email %></td>
        <td><%= employee.department %></td>
        <td><%= employee.job_title %></td>
        <td><%= employee.address %></td>
        <td><%= employee.race %></td>
        <td><%= employee.sex %></td>
        <td><%= employee.credit_card %></td>
        <td><%= employee.height %></td>
        <td><%= employee.marital_status %></td>
        <td><%= employee.startDate %></td>
        <td><%= employee.license %></td>
        <td><%= employee.lunchSpot %></td>
        <td><%= employee.employeeBenft %></td>
        <td><%= employee.vehicle %></td>
        <td><%= employee.vyear %></td>
        <td><%= employee.vmake %></td>
        <td><%= employee.vmodel %></td>
        <td><%= employee.vcarDescr %></td>
        <td><%= employee.vPlate %></td>
        <td><%= employee.photo %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastName %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @employee.job_title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Race:</strong>
  <%= @employee.race %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @employee.sex %>
</p>

<p>
  <strong>Credit card:</strong>
  <%= @employee.credit_card %>
</p>

<p>
  <strong>Height:</strong>
  <%= @employee.height %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @employee.marital_status %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @employee.startDate %>
</p>

<p>
  <strong>License:</strong>
  <%= @employee.license %>
</p>

<p>
  <strong>Lunchspot:</strong>
  <%= @employee.lunchSpot %>
</p>

<p>
  <strong>Employeebenft:</strong>
  <%= @employee.employeeBenft %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @employee.vehicle %>
</p>

<p>
  <strong>Vyear:</strong>
  <%= @employee.vyear %>
</p>

<p>
  <strong>Vmake:</strong>
  <%= @employee.vmake %>
</p>

<p>
  <strong>Vmodel:</strong>
  <%= @employee.vmodel %>
</p>

<p>
  <strong>Vcardescr:</strong>
  <%= @employee.vcarDescr %>
</p>

<p>
  <strong>Vplate:</strong>
  <%= @employee.vPlate %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @employee.photo %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaveatGlobal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>